<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .items {
            width: 100%;
            border-collapse: collapse;
        }

        .items th,
        .items td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        .totals {
            margin-top: 20px;
            width: 100%;
        }

        .right {
            text-align: right;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>Cooca.id</h2>
        <div>Invoice: {{ $invoice->invoice_number }}</div>
        <div>Date: {{ $invoice->issued_at?->format('Y-m-d') ?? $invoice->created_at->format('Y-m-d') }}</div>
    </div>

    <div>
        <strong>Bill To:</strong>
        <div>{{ $customer->name ?? $invoice->customer?->name }}</div>
        <div>{{ $customer->email ?? $invoice->customer?->email }}</div>
    </div>

    <table class="items">
        <thead>
            <tr>
                <th>Description</th>
                <th class="right">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $invoice->transaction?->description ?? 'Subscription Payment' }}</td>
                <td class="right">{{ number_format($invoice->amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <table class="totals">
        <tr>
            <td class="right"><strong>Total:</strong></td>
            <td class="right">{{ number_format($invoice->amount, 2) }}</td>
        </tr>
    </table>

    <div style="margin-top:30px; font-size:10px; color:#666;">
        This is an automated invoice generated by Cooca.id.
    </div>
</body>

</html>
